/**
 * RepoHygiene - License Reporter
 * Generate license reports in various formats
 */

import type { DependencyLicense, LicenseSummary } from '../../types/index.js';
import { groupByLicense } from './policy.js';

/**
 * Generate markdown license report
 */
export function generateMarkdownReport(
    licenses: readonly DependencyLicense[],
    summary: LicenseSummary
): string {
    const lines: string[] = [
        '# License Report',
        '',
        `Generated by RepoHygiene on ${new Date().toISOString()}`,
        '',
        '## Summary',
        '',
        `- **Total packages**: ${summary.total}`,
        `- **Allowed**: ${summary.allowed}`,
        `- **Denied**: ${summary.denied}`,
        `- **Unknown**: ${summary.unknown}`,
        '',
    ];

    // Group by status
    const denied = licenses.filter((l) => l.status === 'denied');
    const unknown = licenses.filter((l) => l.status === 'unknown');
    const allowed = licenses.filter((l) => l.status === 'allowed');

    if (denied.length > 0) {
        lines.push('## ❌ Denied Licenses');
        lines.push('');
        lines.push('| Package | Version | License |');
        lines.push('|---------|---------|---------|');
        for (const dep of denied) {
            lines.push(`| ${dep.name} | ${dep.version} | ${dep.license} |`);
        }
        lines.push('');
    }

    if (unknown.length > 0) {
        lines.push('## ⚠️ Unknown Licenses');
        lines.push('');
        lines.push('| Package | Version | License |');
        lines.push('|---------|---------|---------|');
        for (const dep of unknown) {
            lines.push(`| ${dep.name} | ${dep.version} | ${dep.license} |`);
        }
        lines.push('');
    }

    if (allowed.length > 0) {
        lines.push('## ✅ Allowed Licenses');
        lines.push('');

        // Group allowed by license type
        const grouped = groupByLicense(allowed);
        for (const [license, deps] of grouped) {
            lines.push(`### ${license} (${deps.length})`);
            lines.push('');
            for (const dep of deps) {
                lines.push(`- ${dep.name}@${dep.version}`);
            }
            lines.push('');
        }
    }

    return lines.join('\n');
}

/**
 * Generate CSV license report
 */
export function generateCsvReport(
    licenses: readonly DependencyLicense[]
): string {
    const lines: string[] = [
        'Package,Version,License,Status,Production,Repository',
    ];

    for (const dep of licenses) {
        lines.push(
            [
                dep.name,
                dep.version,
                `"${dep.license}"`,
                dep.status,
                dep.isProduction ? 'yes' : 'no',
                dep.repository ?? '',
            ].join(',')
        );
    }

    return lines.join('\n');
}

/**
 * Generate NOTICE file content
 */
export function generateNoticeFile(
    licenses: readonly DependencyLicense[]
): string {
    const lines: string[] = [
        'THIRD-PARTY SOFTWARE NOTICES AND INFORMATION',
        '============================================',
        '',
        'This project incorporates components from the projects listed below.',
        '',
    ];

    // Group by license
    const grouped = groupByLicense(licenses);

    for (const [license, deps] of grouped) {
        lines.push(`## ${license}`);
        lines.push('');
        for (const dep of deps) {
            lines.push(`- ${dep.name} (${dep.version})`);
            if (dep.repository) {
                lines.push(`  ${dep.repository}`);
            }
        }
        lines.push('');
    }

    return lines.join('\n');
}
